update ci for helpwave tasks
helpwave/mobile-app pull request #178
Opened 2023-01-28 15:57 UTC by DasProffi

closes #169

2023-01-28 21:53 UTC, MaxSchaefer requested changes
Nice! But let's discuss an alternative work-in-progress name for the routing product instead of "helpwave". What do you think about "routing"?

2023-01-28 21:53 UTC, MaxSchaefer commented on .github/workflows/ci.yaml
> +  browserstack-helpwave:
```suggestion
  browserstack:
```

2023-01-28 21:53 UTC, MaxSchaefer commented on .github/workflows/ci.yaml
> +      - name: package helpwave ipa
```suggestion
      - name: package routing ipa
```

2023-01-28 22:43 UTC, DasProffi commented
> Nice! But let's discuss an alternative work-in-progress name for the routing product instead of "helpwave". What do you think about "routing"?

I agree, it's confusing. But this would be something for a team vote and not just the mobile repository.

2023-01-29 08:37 UTC, florian-sabonchi commented on .github/workflows/ci.yaml
> +          mv ./helpwave/build/app/outputs/apk/release/app-release.apk ./helpwave/build/app/outputs/apk/release/app-helpwave.apk
I would suggest to call the APK here just tasks  and helpwave

2023-01-29 12:16 UTC, florian-sabonchi approved these changes

2023-01-29 18:01 UTC, MaxSchaefer approved these changes

2023-01-29 19:32 UTC, merged