RoomOverviewScreen
helpwave/mobile-app pull request #254
Opened 2023-03-11 14:44 UTC by use-to

Closes #183

2023-03-11 22:04 UTC, DasProffi requested changes

2023-03-11 22:04 UTC, DasProffi commented on apps/tasks/lib/screens/room_overview_screen.dart
> +                  ),
dont use custom fontWeight use a TextStyle from texttheme in stead or mark with a todo for the texttheme/themeUpdate

2023-03-11 22:07 UTC, DasProffi commented
The Screen and BedCards look great

2023-03-19 18:27 UTC, florian-sabonchi commented
What is your perspective on ascribing the Pull Request a provisional classification of 'Draft' in instances when it is not presently undergoing proactive modifications?

2023-03-31 13:17 UTC, use-to commented on apps/tasks/lib/main.dart
> +          ),
Applying "ignored for now" cause bn-bar should be fine.

2023-03-31 13:49 UTC, use-to commented on apps/tasks/lib/components/task_status_pill.dart
> +                fontSize: 12.5,
Also marked as `// TODO` for theming update

2023-04-02 11:30 UTC, DasProffi requested changes

2023-04-02 11:30 UTC, DasProffi commented on apps/tasks/lib/screens/room_overview_screen.dart
> +          padding: const EdgeInsets.only(bottom: 25),
```suggestion
          padding: const EdgeInsets.only(bottom: distanceDefault),
```

2023-04-02 11:30 UTC, DasProffi commented on apps/tasks/lib/components/task_status_pill_box.dart
> +    const double paddingHorizontal = 6;
```suggestion
    const double paddingHorizontal = paddingTiny;
```

add `const double paddingTiny= 6;` to constants file
or make the paddingHorizontal a attribute of the widget

2023-04-02 11:30 UTC, DasProffi commented on apps/tasks/lib/components/task_status_pill.dart
> +            const SizedBox(width: 4),
Make this an attribute of the widget or use a predefined style constant like `distanceTiny`

2023-04-02 17:30 UTC, DasProffi approved these changes

2023-04-02 17:50 UTC, merged