Add swipe gestures to delete and mark a task as done
helpwave/mobile-app pull request #259
Opened 2023-03-14 18:11 UTC by florian-sabonchi

closes #258

2023-03-14 22:59 UTC, DasProffi requested changes

2023-03-14 22:59 UTC, DasProffi commented on apps/tasks/lib/screens/my_tasks_screen.dart
> +                          // TODO: mark task as done
```suggestion
                          // TODO: add API Call
                          _items[index]['isChecked'] = true;
```

2023-03-14 23:01 UTC, DasProffi commented on apps/tasks/lib/screens/my_tasks_screen.dart
> +                          // TODO: mark task as done
Could also be `_items[index]['isChecked'] = !_items[index]['isChecked'], but this would require a different dimissable background for endToStart

2023-03-14 23:02 UTC, DasProffi commented
Do we want to move the dimissable Widget als into the TaskTile widget, because they are always used together (at least ffor now) or do we want to write another widget that does this wrapping?

2023-03-15 07:55 UTC, florian-sabonchi commented
> Do we want to move the dimissable Widget als into the TaskTile widget, because they are always used together (at least ffor now) or do we want to write another widget that does this wrapping?

Yes sounds good to me

2023-03-18 15:03 UTC, DasProffi requested changes

2023-03-18 15:03 UTC, DasProffi commented on apps/tasks/lib/components/task_list_tile.dart
> +              child: Icon(Icons.done),
change the color and icon when task is already in state done or remove the ability to reopen a task on left swipe

2023-03-18 20:45 UTC, DasProffi approved these changes

2023-03-18 20:48 UTC, DasProffi commented on apps/tasks/lib/screens/my_tasks_screen.dart
> +                      },
Maybe move this directly to the `TaskListTile` Widget

2023-03-19 12:51 UTC, DasProffi approved these changes

2023-03-19 13:22 UTC, merged