draft for auth service
helpwave/mobile-app pull request #283
Opened 2023-09-16 18:01 UTC by DasProffi

## Which issues does this pull request close?
closes #277

2023-09-20 21:07 UTC, MaxSchaefer requested changes

2023-09-20 21:07 UTC, MaxSchaefer commented on packages/helpwave_service/lib/src/auth/authentication_service.dart
> +    String redirectUrl, {
The redirectUrl should be non-configurable by the caller due to the fact that the caller should not create its own callback server.

2023-09-20 21:07 UTC, MaxSchaefer commented on packages/helpwave_service/lib/src/auth/authentication_service.dart
> +    String discoveryUrl,
We could fallback here as well to the default

2023-09-20 21:07 UTC, MaxSchaefer commented on packages/helpwave_service/lib/src/auth/authentication_service.dart
> +      // TODO this does't work :(
Only on Android. See iOS via BrowserStack

2023-09-20 21:07 UTC, MaxSchaefer commented on apps/tasks/lib/screens/landing_screen.dart
> +          onPressed: () => {AuthenticationService().authenticate("https://auth.helpwave.de", "http://localhost:3000/")}//Navigator.of(context).pushReplacement(MaterialPageRoute(builder: (context) =>
Please add a second button instead until the fake-tokens are implemented

2023-09-20 21:07 UTC, MaxSchaefer commented on packages/helpwave_service/lib/src/auth/authentication_service.dart
`clientId` and `discoveryUrl` should be env/build variable

2023-09-23 14:28 UTC, LauraLobster approved these changes

2023-10-28 18:27 UTC, MaxSchaefer approved these changes

2023-10-28 18:27 UTC, MaxSchaefer commented on packages/helpwave_service/lib/src/auth/authentication_service.dart
Add comment

2023-10-28 18:27 UTC, MaxSchaefer commented on packages/helpwave_service/lib/src/auth/authentication_service.dart
> +      organizations: /* TODO userInfo.getTyped("organizations") ?? */ [],
All of this should be non-empty

2023-10-28 21:58 UTC, DasProffi commented on packages/helpwave_service/lib/src/auth/authentication_service.dart
See https://github.com/helpwave/mobile-app/issues/424

2023-10-29 08:21 UTC, merged