add TaskCards and aggregate on my tasks screen
helpwave/mobile-app pull request #355
Opened 2023-09-27 14:55 UTC by DasProffi

## Which issues does this pull request close?
closes #349

2023-09-28 14:57 UTC, florian-sabonchi commented on apps/tasks/lib/components/task_card.dart
> +    String result = context.localization!.dueIn;
Please remove the unnecessary else

2023-09-28 14:58 UTC, florian-sabonchi commented on apps/tasks/lib/components/task_card.dart
> +    String result = context.localization!.dueIn;
and i think it would make sense use a switch statement instead

2023-09-28 15:04 UTC, florian-sabonchi commented on apps/tasks/lib/components/task_card.dart
> +    String result = context.localization!.dueIn;
`class MyLocalizations {
  static String minutes(int count) => Intl.plural(
    count,
    one: '1 minute',
    other: '$count minutes',
    name: 'minutes',
  );
}`

2023-09-28 18:53 UTC, florian-sabonchi requested changes

2023-09-28 18:53 UTC, florian-sabonchi commented on apps/tasks/lib/components/task_card.dart
> +  String getDueText(BuildContext context) {
```suggestion
   String getDueText(BuildContext context) {
    String result = context.localization!.dueIn;
    if (task.dueDate == null) {
      return "$result -";
    }

    if (task.isOverdue) {
      return context.localization!.overdue;
    }

    if (task.inNextHour) {
      return "$result ${context.localization!.nMinutes(task.remainingTime.inMinutes)}";
    }

    if (task.inNextTwoDays) {
      return "$result ${context.localization!.nHours(task.remainingTime.inHours)}";
    }

    return "$result ${context.localization!.nDays(task.remainingTime.inDays)}";
  }
```

2023-09-28 21:38 UTC, MaxSchaefer approved these changes

2023-09-29 13:35 UTC, florian-sabonchi approved these changes

2023-09-29 13:59 UTC, merged