Issue/32 splash screen
helpwave/mobile-app pull request #39
Opened 2022-10-22 18:03 UTC by DasProffi

closes #32

Testing Information:
- Test with android <11
- Test with android >=11

2022-10-22 18:53 UTC, Florian-Sabonchi commented
```E/AndroidRuntime(31533): FATAL EXCEPTION: main
E/AndroidRuntime(31533): Process: de.helpwave.helpwave, PID: 31533
E/AndroidRuntime(31533): java.lang.RuntimeException: Unable to instantiate activity ComponentInfo{de.helpwave.helpwave/de.helpwave.helpwave.MainActivity}: java.lang.ClassNotFoundException: Didn't find class "de.helpwave.helpwave.MainActivity" on path: DexPathList[[zip file "/data/app/~~w5DIFd99Wf0Lz1d0wc51Yw==/de.helpwave.helpwave-c55BETZAbf6KrHeCjisgIw==/base.apk"],nativeLibraryDirectories=[/data/app/~~w5DIFd99Wf0Lz1d0wc51Yw==/de.helpwave.helpwave-c55BETZAbf6KrHeCjisgIw==/lib/arm64, /data/app/~~w5DIFd99Wf0Lz1d0wc51Yw==/de.helpwave.helpwave-c55BETZAbf6KrHeCjisgIw==/base.apk!/lib/arm64-v8a, /system/lib64, /system_ext/lib64]]
E/AndroidRuntime(31533): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3583)
E/AndroidRuntime(31533): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3814)
E/AndroidRuntime(31533): 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:101)
E/AndroidRuntime(31533): 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
E/AndroidRuntime(31533): 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
E/AndroidRuntime(31533): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2309)
E/AndroidRuntime(31533): 	at android.os.Handler.dispatchMessage(Handler.java:106)
E/AndroidRuntime(31533): 	at android.os.Looper.loopOnce(Looper.java:201)
E/AndroidRuntime(31533): 	at android.os.Looper.loop(Looper.java:288)
E/AndroidRuntime(31533): 	at android.app.ActivityThread.main(ActivityThread.java:7904)
E/AndroidRuntime(31533): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(31533): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
E/AndroidRuntime(31533): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:952)
E/AndroidRuntime(31533): Caused by: java.lang.ClassNotFoundException: Didn't find class "de.helpwave.helpwave.MainActivity" on path: DexPathList[[zip file "/data/app/~~w5DIFd99Wf0Lz1d0wc51Yw==/de.helpwave.helpwave-c55BETZAbf6KrHeCjisgIw==/base.apk"],nativeLibraryDirectories=[/data/app/~~w5DIFd99Wf0Lz1d0wc51Yw==/de.helpwave.helpwave-c55BETZAbf6KrHeCjisgIw==/lib/arm64, /data/app/~~w5DIFd99Wf0Lz1d0wc51Yw==/de.helpwave.helpwave-c55BETZAbf6KrHeCjisgIw==/base.apk!/lib/arm64-v8a, /system/lib64, /system_ext/lib64]]
E/AndroidRuntime(31533): 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:259)
E/AndroidRuntime(31533): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
E/AndroidRuntime(31533): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
E/AndroidRuntime(31533): 	at android.app.AppComponentFactory.instantiateActivity(AppComponentFactory.java:95)
E/AndroidRuntime(31533): 	at androidx.core.app.CoreComponentFactory.instantiateActivity(CoreComponentFactory.java:45)
E/AndroidRuntime(31533): 	at android.app.Instrumentation.newActivity(Instrumentation.java:1333)
E/AndroidRuntime(31533): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3570)
E/AndroidRuntime(31533): 	... 12 more```

2022-10-22 19:02 UTC, DasProffi commented
How did you test it? Worked for me on android 11 and 13

2022-10-22 19:06 UTC, Florian-Sabonchi commented
> How did you test it? Worked for me on android 11 and 13

Pulled your Branch and compiled in android Studio

2022-10-22 19:08 UTC, Florian-Sabonchi commented
Coud be a Problem with Graphen OS i dont know bevore approving we need to verify that and also test on IOS

2022-10-22 19:27 UTC, DasProffi commented
the mobile brnach is android and ios only, web crashes, becasue of flutter_osm

2022-10-23 10:42 UTC, use-to requested changes

2022-10-23 10:42 UTC, use-to commented on pubspec.yaml
> +  # list giving the asset and other descriptors for assetsthe font. For
TYPOOO :D

2022-10-23 11:08 UTC, use-to approved these changes

2022-10-23 11:45 UTC, use-to commented
Waiting for @MaxSchaefer `s approval!

2022-10-23 17:36 UTC, MaxSchaefer approved these changes

2022-10-23 18:06 UTC, merged