Issue/504 use lower case name
helpwave/mobile-app pull request #505
Opened 2024-02-11 14:44 UTC by florian-sabonchi

## Which issues does this pull request close?
closes #

## [OPTIONAL] Give testing instructions to reviewers

2024-02-18 23:32 UTC, MaxSchaefer commented
Was there a linter warning or what is the reasoning behind this pr? If thats a convention, please update our linter.

2024-02-19 17:18 UTC, DasProffi requested changes

2024-02-19 17:18 UTC, DasProffi commented on apps/tasks/lib/services/patient_svc.dart
> +import 'package:tasks/services/current_ward_svc.dart';
Not part of this PR
```suggestion
```

2024-02-19 17:18 UTC, DasProffi commented on apps/tasks/lib/services/patient_svc.dart
> +        ),
Not part of this PR
```suggestion
        metadata: GRPCClientService().getTaskServiceMetaData(),
```

2024-02-21 18:57 UTC, DasProffi approved these changes

2024-02-21 19:02 UTC, merged