Issue/541 properties bottom sheets
helpwave/mobile-app pull request #545
Opened 2024-11-14 13:01 UTC by DasProffi

## Which issues does this pull request close?
closes #541

## [OPTIONAL] Give testing instructions to reviewers

2024-11-16 11:22 UTC, DasProffi commented
@MaxSchaefer The UI and most functions except changing the select options work, but there is an issue with the authentication and consistency which is not implemented yet

2024-11-27 16:19 UTC, felixevers requested changes
[Screencast from 2024-11-27 17-18-52.webm](https://github.com/user-attachments/assets/0fb63e02-46c4-4490-9a9b-b667e5e84bda)

2024-11-30 13:56 UTC, felixevers reviewed
We could defentily create some more issues out of the `// TODO` comments. But lets wait for `v1-tasks`

2024-12-01 17:10 UTC, felixevers approved these changes

2024-12-02 11:30 UTC, merged