add emergency chat room
helpwave/mobile-app pull request #63
Opened 2022-11-19 17:02 UTC by DasProffi

closes #53

2022-11-20 12:42 UTC, DasProffi commented
| Light | Dark |
| -- | -- |
|<img src="https://user-images.githubusercontent.com/67233923/202902298-fb192e90-6a23-4791-a217-c27b44addfba.JPG" width="250" height="400" /> | <img src="https://user-images.githubusercontent.com/67233923/202902299-4b7985d0-6c93-48f1-bc1e-2445fada6979.JPG" width="250" height="400" /> |

2022-11-21 23:54 UTC, use-to requested changes

2022-11-21 23:54 UTC, use-to commented on lib/pages/emergency_chat.dart
> +                              size: iconSizeSmall,
make it even smaller

2022-11-21 23:54 UTC, use-to commented on lib/pages/emergency_chat.dart
> +                      child: TextField(
add placeholder text

2022-11-21 23:54 UTC, use-to commented on lib/pages/emergency_chat.dart
> +      appBar: AppBar(
An AppBar shadow would be nice

2022-11-21 23:54 UTC, use-to commented on lib/pages/emergency_chat.dart
> +      messages.add({"isFromEmergencyRoom": false, "message": _controller.text});
`setState`

2022-11-21 23:54 UTC, use-to commented on lib/pages/emergency_chat.dart
> +      messages.add({"isFromEmergencyRoom": false, "message": _controller.text});
trim the message

2022-11-21 23:54 UTC, use-to commented on lib/pages/emergency_chat.dart
> +                          child: IconButton(
disabled this button while there is no input (only spaces included)

2022-11-21 23:54 UTC, use-to commented on lib/pages/emergency_chat.dart
> +            children: [
add some spacing here

2022-11-21 23:54 UTC, use-to commented on lib/pages/emergency_chat.dart
> +            children: [
`topMargin`

2022-11-21 23:54 UTC, use-to commented on lib/pages/emergency_chat.dart
> +            const CircleAvatar(
remove this

2022-11-22 20:29 UTC, DasProffi commented
<img src="https://user-images.githubusercontent.com/67233923/203414442-8412e511-88b8-49f3-93a2-ead8be961356.JPG" width="240" height ="400">

2022-11-22 23:47 UTC, use-to requested changes

2022-11-22 23:47 UTC, use-to commented on lib/pages/emergency_chat.dart
> +                            }
```suggestion
                          bool couldSend = _controller.text.trim().isNotEmpty;
                          if (canSend != couldSend) {
                            setState(() {
                              canSend = couldSend;
                            });
                          }
```

2022-11-22 23:47 UTC, use-to commented on lib/pages/emergency_chat.dart
> +                                : Theme.of(context).colorScheme.secondary,
Is there no button `disabled` color in theme definition?

2022-11-27 14:18 UTC, use-to approved these changes

2022-11-27 14:19 UTC, merged